/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Commissions: () => import('#controllers/commissions_controller'),
  Statics: () => import('#controllers/statics_controller'),
}
